/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package granth;
import java.sql.*;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
//import javax.swing.DefaultListModel;
/**
/**
 *
 * @author MOHIT
 */
public class bookissue extends javax.swing.JInternalFrame {
Connection c=null;
Statement s,p,j,i,k;
//Statement p=null;
ResultSet rs=null;

ResultSet ra=null;


ResultSet rp=null;ResultSet ri=null;
ResultSet kk=null;

///String qry;


    /**
     * Creates new form bookissue
     */
    public bookissue() {
        
        initComponents();
         try{
            c=DriverManager.getConnection("jdbc:mysql://localhost:3306/mohit","root","");
                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(rootPane,e.getMessage());
                    }
        t2.setEnabled(false);
         t3.setEnabled(false);
          t6.setEnabled(false);
           t5.setEnabled(false);
            
          
                 
           
           

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(586, 466));
        setMinimumSize(new java.awt.Dimension(586, 466));
        setPreferredSize(new java.awt.Dimension(586, 466));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 224, 39, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Book Title");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 257, -1, -1));
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 255, 177, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Authors");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 288, -1, -1));
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 286, 240, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Member ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 53, -1, -1));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 51, 47, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Enter Issue Date");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 319, -1, -1));

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        t2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                t2PropertyChange(evt);
            }
        });
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 82, 178, -1));
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 317, 112, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 84, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Membership Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 113, -1, -1));

        t3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 112, 100, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, 605, 0));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Accession No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 226, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("MEMBER DETAILS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 153));
        jLabel6.setText("BOOK DETAILS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 393, -1, -1));

        jButton2.setText("ISSUE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 393, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 198, 570, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/granth/abstract_colour_background_orange.jpg"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(586, 466));
        jLabel9.setMinimumSize(new java.awt.Dimension(586, 466));
        jLabel9.setPreferredSize(new java.awt.Dimension(586, 466));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed

    }//GEN-LAST:event_t2ActionPerformed

    private void t2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_t2PropertyChange

    }//GEN-LAST:event_t2PropertyChange

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed

    }//GEN-LAST:event_t2KeyPressed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed

    }//GEN-LAST:event_t1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     String q="select name,date from member";
     String g="insert into issue1 values('"+t1.getText()+"','"+t4.getText()+"','"+t7.getText()+"')";
        String qry="insert into issue values('"+t1.getText()+"','"+t4.getText()+"','"+t7.getText()+"')";
        String r="select title,author from books";
        String p="delete from manage where no='"+t4.getText()+"'";
try{
s=c.createStatement();
rs=s.executeQuery(q);
          rs.next();
           t2.setText(rs.getString("name"));
           t3.setText(rs.getString("DATE"));
 }
        catch(Exception e)
                {JOptionPane.showMessageDialog(rootPane,e.getMessage());
                
                }
Statement k=null;
try{
    k=c.createStatement();
    k.executeUpdate(g);
    
}catch(Exception e){JOptionPane.showMessageDialog(null,e.getMessage());
    
}
try{
             s=c.createStatement();
             ra=s.executeQuery(r);
             ra.next();
             t5.setText(ra.getString("title"));
             t6.setText(ra.getString("author"));
                                
        }   
        catch(Exception e){
        JOptionPane.showMessageDialog(rootPane,e.getMessage());}
                try{
            
           s=c.createStatement();
           s.executeUpdate(qry);
        JOptionPane.showMessageDialog(rootPane,"BOOK ISSUED");}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
                
                
                try{
k=c.createStatement();
k.executeUpdate(p);
          
 }
        catch(Exception e)
                {JOptionPane.showMessageDialog(rootPane,e.getMessage());
                
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
t1.setText("");
       t4.setText("");t2.setText("");

t7.setText("");
t3.setText("");
t5.setText("");
t6.setText("");        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    // End of variables declaration//GEN-END:variables
}
