/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package granth;
import java.sql.*;

import javax.swing.JOptionPane;
/**
 *
 * @author MOHIT
 */
public class memsearch extends javax.swing.JInternalFrame {
Connection c=null;
Statement s;
ResultSet rs=null;
String q="select * from member";
    /**
     * Creates new form memsearch
     */
    public memsearch() {
        initComponents();
        a.setEnabled(false);
     as.setEnabled(false);
     sa.setEnabled(false);
     t2.setEditable(false);
     t3.setEditable(false);
     t4.setEditable(false);
     t5.setEditable(false);
     t6.setEditable(false);
     t.setEditable(false);
     
        try{
            c=DriverManager.getConnection("jdbc:mysql://localhost:3306/mohit","root","");
                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(rootPane,e.getMessage());
                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        as = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        a = new javax.swing.JButton();
        sa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        t = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setMinimumSize(new java.awt.Dimension(606, 402));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 113, -1, -1));

        t5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 212, 100, -1));

        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 339, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Membership Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 241, -1, -1));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 83, 47, -1));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 160, 118, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 590, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Member ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 88, -1, -1));

        t6.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 237, 100, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 306, 570, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 139, -1, -1));

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        t2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                t2PropertyChange(evt);
            }
        });
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 108, 178, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Membership Fee");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 216, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MEMBER'S CONSOLE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 570, -1));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 134, 272, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Phone/Mobile");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 165, -1, -1));

        as.setText("NEXT");
        as.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asActionPerformed(evt);
            }
        });
        getContentPane().add(as, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 339, -1, -1));

        jButton1.setText("FIRST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        a.setText("PREVIOUS");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        sa.setText("LAST");
        sa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saActionPerformed(evt);
            }
        });
        getContentPane().add(sa, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 339, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("MEMBERSHIP");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 191, -1, -1));

        t.setText(" ");
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 186, 150, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/granth/abstract_colour_background_orange.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 670, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        t.setText("");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed

    }//GEN-LAST:event_t2ActionPerformed

    private void t2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_t2PropertyChange

    }//GEN-LAST:event_t2PropertyChange

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed

    }//GEN-LAST:event_t2KeyPressed

    private void asActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asActionPerformed

        try{

            if(rs.next())
            {
                t1.setText(rs.getString("id"));
                t2.setText(rs.getString("name"));
                t3.setText(rs.getString("address"));
                t4.setText(rs.getString("phone_no"));
                t5.setText(rs.getString("fee"));
                t6.setText(rs.getString("date"));
                t.setText(rs.getString("membership"));
            }
            else{
            JOptionPane.showMessageDialog(rootPane,"You Are At The Last Record ");
        }}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());

        }
    }//GEN-LAST:event_asActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
            s=c.createStatement();
            rs=s.executeQuery(q);
            if(rs.first())
            {
                t1.setText(rs.getString("id"));
                t2.setText(rs.getString("name"));
                t3.setText(rs.getString("address"));
                t4.setText(rs.getString("phone_no"));
                t5.setText(rs.getString("fee"));
                t6.setText(rs.getString("date"));
                t.setText(rs.getString("membership"));
                a.setEnabled(true);
                as.setEnabled(true);
                sa.setEnabled(true);
            }
            else
            JOptionPane.showMessageDialog(rootPane,"You Are Already At The First Record");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        try{

            if(rs.previous())
            {
                t1.setText(rs.getString("id"));
                t2.setText(rs.getString("name"));
                t3.setText(rs.getString("address"));
                t4.setText(rs.getString("phone_no"));
                t5.setText(rs.getString("fee"));
                t6.setText(rs.getString("date"));
                t.setText(rs.getString("membership"));
            }
            else
            JOptionPane.showMessageDialog(rootPane,"You Are At The First Record ");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());

        }
    }//GEN-LAST:event_aActionPerformed

    private void saActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saActionPerformed
        try{

         if(rs.last())
            {
                t1.setText(rs.getString("id"));
                t2.setText(rs.getString("name"));
                t3.setText(rs.getString("address"));
                t4.setText(rs.getString("phone_no"));
                t5.setText(rs.getString("fee"));
                t6.setText(rs.getString("date"));
                t.setText(rs.getString("membership"));
            }
         else{
            JOptionPane.showMessageDialog(rootPane,"You Are Already At The Last Record ");
        }}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());

        }
    }//GEN-LAST:event_saActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton as;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton sa;
    private javax.swing.JTextField t;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
